# Schema for the configuration files of the API Response check module.

api_response_check.settings:
  type: config_object
  label: 'API Response settings'
  mapping:
    api_inputs:
      type: text
      label: 'API URL'
