view_mode_page.pattern:
  type: config_entity
  label: 'View mode page pattern'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    uuid:
      type: string
      label: 'UUID'
    type:
      type: string
      label: 'Type'
    pattern:
      type: string
      label: 'Pattern'
    selection_criteria:
      type: sequence
      label: 'Selection criteria'
    selection_logic:
      type: string
      label: 'Selection logic'
    weight:
      type: integer
      label: 'Weight'
    relationships:
      type: sequence
      lable: 'Releationships'
